[{
	lib: "Company",
	src: "script/company.js",
}, {
	lib: "ServiceRouter",
	src: (window.bLocal ? "/nammour.com/cms/" : "") + "script/ServiceRouter.js",
}, {
	lib: "FormHelper",
	src: (window.bLocal ? "/nammour.com/ems/" : "") + "script/FormHelper.js",
}, {
	lib: "FontAwesome",
	css: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css',
	cache: true,
}, {
	lib: "WebIX",
	src: "http://cdn.webix.com/edge/webix.js",
	css: "https://cdn.webix.com/edge/webix.css",
	cache: true,
	tools: [],
}, {
	lib: "TotalJS",
	src: "https://cdn.componentator.com/spa.min@19.js",
	css: "https://cdn.componentator.com/spa.min@19.css",
	cache: true,
	tools: ['FileSystem'],
}, {
	lib: "Blockly",
	src: ["https://unpkg.com/blockly/blockly_compressed.js", "https://unpkg.com/blockly/blocks_compressed.js", "https://unpkg.com/blockly/javascript_compressed.js", "https://unpkg.com/blockly/msg/en.js"],
	cache: true,
}, {
	lib: "Supabase",
	src: "https://unpkg.com/@supabase/supabase-js@2",
	cache: true,
	tools: ["Supabase"],
}, {
	lib: "ESLint",
	src: "https://cdn.jsdelivr.net/npm/eslint-plugin-browser@0.0.0/lib/index.min.js",
	cache: true,
}, {
	lib: "AMQPLib",
	src: "https://cdn.jsdelivr.net/npm/amqplib@0.10.4/channel_api.min.js",
	cache: true,
}, {
	lib: "TogetherJS",
	src: "https://togetherjs.com/togetherjs-min.js",
	cache: true,
}, {
	lib: "VueJS",
	src: "https://unpkg.com/vue@3/dist/vue.global.js",
	cache: true,
}, {
	lib: "JMESPath",
	src: "https://cdnjs.cloudflare.com/ajax/libs/jmespath/0.14.0/jmespath.min.js",
	cache: true,
}, {
	lib: "PyScript",
	src: "https://pyscript.net/latest/core.js",
	module: true,
	cache: true,
}, {
	lib: "ZopfliJS",
	src: "https://cdn.jsdelivr.net/gh/imaya/zopfli.js/bin/zopfli.raw.min.js",
	cache: true,
}, {
	lib: "LogHTML",
	src: "https://cdn.jsdelivr.net/npm/console-log-html@2.0.2/console-log-html.min.js",
	cache: true,
	load: modules => document.getElementById("LogHTML") ? ConsoleLogHTML.connect(document.getElementById("LogHTML")) : '',
}, {
	lib: "Neo4j",
	src: "https://cdn.jsdelivr.net/npm/neo4j-driver@5.6.0/lib/browser/neo4j-web.min.js",
	cache: true,
}, {
	lib: "AirTable",
	src: "https://cdn.jsdelivr.net/npm/airtable@0.5.8/build/airtable.browser.js",
	cache: true,
}, {
	lib: "MQTT",
	src: "https://cdnjs.cloudflare.com/ajax/libs/mqtt/5.10.1/mqtt.min.js",
	cache: true,
}, {
	lib: "ProtoBufJS",
	src: "https://cdn.jsdelivr.net/npm/protobufjs/dist/protobuf.min.js",
	cache: true,
}, {
	lib: "BPMN-JS",
	src: "https://cdn.jsdelivr.net/npm/bpmn-js@10.2.1/dist/bpmn-viewer.production.min.js",
	cache: true,
}, {
	lib: "SQLJS",
	src: ['https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.12.0/sql-wasm.js', 'https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.12.0/worker.sql-wasm.js'],
	cache: true,
	load: async modules => {
		window.SQL = await initSqlJs({
			locateFile: file => `https://cdnjs.cloudflare.com/ajax/libs/sql.js/1.12.0/${file}`
		});
	},
	tools: ['SqlDB'],
}, {
	lib: "JSO",
	src: "https://cdn.jsdelivr.net/npm/jso-ng@1.0.5/src/index.min.js",
	cache: true,
}, {
	lib: "Konva",
	src: "https://cdnjs.cloudflare.com/ajax/libs/konva/8.4.2/konva.min.js",
	cache: true,
}, {
	lib: 'ObjectHash',
	src: 'https://cdn.jsdelivr.net/npm/object-hash@3.0.0/dist/object_hash.min.js',
	cache: true,
}, {
	lib: 'LokiJS',
	src: 'https://cdnjs.cloudflare.com/ajax/libs/lokijs/1.5.12/lokijs.min.js',
	cache: true,
}, {
	lib: "Socket.IO",
	src: "https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.7.0/socket.io.min.js",
	cache: true,
}, {
	lib: "P5JS",
	src: ["https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.1/p5.min.js" /*, "https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.3.1/addons/p5.sound.min.js"*/ ],
	cache: true,
}, {
	lib: "DynaForm",
	src: (window.bLocal ? "/nammour.com/ems/" : "") + "script/DynaForm.js",
	css: "http://voky.com.ua/showcase/sky-forms/examples/css/sky-forms.css",
	requires: ["EasyUI"],
}, {
	lib: "EasyUI",
	_src: ["https://cdn.jsdelivr.net/npm/jquery-easyui/js/jquery.easyui.min.js"],
	css: ["https://www.jeasyui.com/easyui/themes/icon.css"].concat(["https://www.jeasyui.com/easyui/themes/material/easyui.css"]), //.concat(["https://www.jeasyui.com/easyui/themes/material-teal/easyui.css"]).concat(["https://www.jeasyui.com/easyui/themes/default/easyui.css"]),
	_css: ["https://cdn.jsdelivr.net/npm/jquery-easyui/css/easyui.min.css"],
	src: ["https://www.jeasyui.com/easyui/jquery.easyui.min.js", "https://www.jeasyui.com//easyui/datagrid-filter.js"],
	cache: true,
	requires: ['FontAwesome'],
}, {
	lib: 'dot-object',
	src: 'https://cdn.jsdelivr.net/npm/dot-object@2.1.5/dist/dot-object.min.js',
	cache: true,
	tools: [],
}, {
	lib: 'ZangoDB',
	src: 'https://unpkg.com/zangodb@latest/dist/zangodb.min.js',
	cache: true,
}, {
	lib: "RevealJS",
	src: ['https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.0/reveal.min.js', 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.0/plugin/zoom/plugin.min.js', 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.0/plugin/search/search.min.js', 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.0/plugin/notes/notes.min.js', 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.0/plugin/math/math.min.js', 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.0/plugin/markdown/markdown.min.js', 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.0/plugin/highlight/highlight.min.js'],
	css: ['https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.0/theme/moon.min.css', 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.0/reset.min.css', 'https://cdnjs.cloudflare.com/ajax/libs/reveal.js/4.1.0/reset.min.css'],
	cache: true,
}, {
	lib: "QRCode",
	src: "https://cdnjs.cloudflare.com/ajax/libs/qrcode-generator/1.4.4/qrcode.min.js",
	cache: true,
}, {
	lib: "OTPAuth",
	src: "https://cdnjs.cloudflare.com/ajax/libs/otpauth/7.0.2/otpauth.umd.min.js",
	cache: true,
	requires: ["QRCode"],
}, {
	lib: "Mermaid",
	src: "https://cdnjs.cloudflare.com/ajax/libs/mermaid/9.1.7/mermaid.min.js",
	cache: true,
}, {
	lib: "SwaggerClient",
	src: "https://unpkg.com/swagger-client",
	cache: true,
}, {
	lib: "Lodash",
	src: "https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.js",
	cache: true,
}, {
	lib: "JSForce",
	src: "https://cdnjs.cloudflare.com/ajax/libs/jsforce/1.11.1/jsforce.min.js",
	cache: true,
}, {
	lib: 'Flatted',
	src: 'https://unpkg.com/flatted@3.2.7/min.js',
	cache: true,
}, {
	lib: "Axios",
	src: "https://cdnjs.cloudflare.com/ajax/libs/axios/1.6.8/axios.min.js",
	cache: true,
	tools: [],
}, {
	lib: "Obfuscator",
	src: "https://cdn.jsdelivr.net/npm/javascript-obfuscator/dist/index.browser.js",
	cache: true,
}, {
	lib: "Esprima",
	src: "https://cdn.jsdelivr.net/npm/esprima@4.0.1/dist/esprima.min.js",
	cache: true,
}, {
	lib: "Acron",
	src: "https://cdnjs.cloudflare.com/ajax/libs/acorn/8.4.1/acorn.min.js",
	cache: true,
}, {
	lib: "D3",
	src: "https://cdnjs.cloudflare.com/ajax/libs/d3/6.5.0/d3.min.js",
	cache: true,
}, {
	lib: "SemanticUI",
	src: "https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js",
	css: "https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css",
}, {
	lib: "Bootstrap",
	css: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css",
	src: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js",
	cache: true,
}, {
	lib: "Alpaca",
	cache: true,
	src: "//cdn.jsdelivr.net/npm/alpaca@1.5.27/dist/alpaca/bootstrap/alpaca.min.js",
	css: "//cdn.jsdelivr.net/npm/alpaca@1.5.27/dist/alpaca/bootstrap/alpaca.min.css",
}, {
	lib: "JSONata",
	src: "https://cdn.jsdelivr.net/npm/jsonata@2.0.5/jsonata.min.js",
	cache: true,
}, {
	lib: "JSONPath",
	src: "https://cdn.jsdelivr.net/npm/jsonpath/jsonpath.min.js",
	cache: true,
}, {
	lib: "MaterialUI",
	src: "https://unpkg.com/@material-ui/core@latest/umd/material-ui.development.js",
	module: true,
}, {
	lib: "knockout",
	src: "https://cdnjs.cloudflare.com/ajax/libs/knockout/3.5.0/knockout-min.js",
}, {
	lib: "ArcGIS",
	src: "https://js.arcgis.com/4.14/",
	css: "https://js.arcgis.com/4.14/esri/css/main.css",
}, {
	lib: "jsPDF",
	src: "https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.3.1/jspdf.umd.min.js",
}, {
	lib: "html2canvas",
	src: "https://html2canvas.hertzen.com/dist/html2canvas.min.js",
}, {
	lib: "SweetAlert",
	src: "https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js",
	css: "https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css"
}, {
	lib: "PouchDB",
	src: "https://cdnjs.cloudflare.com/ajax/libs/pouchdb/7.1.1/pouchdb.min.js",
}, {
	lib: "JSZip",
	src: ["https://cdnjs.cloudflare.com/ajax/libs/jszip/3.7.1/jszip.min.js", "https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"],
}, {
	lib: "BabelJS",
	src: "https://unpkg.com/@babel/standalone/babel.min.js",
	cache: true,
}, {
	lib: "DataTables",
	src: "https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.19/js/jquery.dataTables.min.js",
	css: "https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.19/css/jquery.dataTables.min.css",
}, {
	lib: "BT Tables",
	src: "//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.9.1/bootstrap-table.min.js",
	css: "//cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.9.1/bootstrap-table.min.css"
}, {
	lib: "Ionic",
	src: "https://cdnjs.cloudflare.com/ajax/libs/ionic/1.3.2/js/ionic.min.js",
	css: "https://cdnjs.cloudflare.com/ajax/libs/ionic/1.3.2/css/ionic.min.css"
}, {
	lib: "uuid",
	src: "https://esm.run/uuid",
	_src: 'https://jspm.dev/uuid',
	cache: true,
	module: true,
	load: modules => {
		window.uuidv = modules[0].v7;
	},
}, {
	lib: "sql-formatter",
	src: "https://cdnjs.cloudflare.com/ajax/libs/sql-formatter/7.0.0/sql-formatter.min.js",
	cache: true,
}, {
	lib: "ThreeJS",
	src: "https://cdnjs.cloudflare.com/ajax/libs/three.js/r74/three.js",
}, {
	lib: "Kendo UI",
	src: "https://kendo.cdn.telerik.com/2016.1.112/js/kendo.all.min.js",
	css: ["https://kendo.cdn.telerik.com/2016.1.112/styles/kendo.common.min.css", "http://kendo.cdn.telerik.com/2016.1.112/styles/kendo.material.min.css"]
}, {
	lib: "Semantic UI",
	src: "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js",
	css: "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css"
}, {
	lib: "LZ-String",
	src: "https://cdnjs.cloudflare.com/ajax/libs/lz-string/1.4.4/lz-string.min.js",
	cache: true,
}, {
	lib: "JQuery Form",
	src: "https://cdnjs.cloudflare.com/ajax/libs/jquery.form/3.51/jquery.form.min.js",
}, {
	lib: "Sencha",
	src: 'https://cdnjs.cloudflare.com/ajax/libs/extjs/6.2.0/ext-all.js',
	cache: true,
}, {
	lib: "TwoJS",
	src: 'https://cdnjs.cloudflare.com/ajax/libs/two.js/0.8.10/two.min.js',
	cache: true,
}, {
	lib: "XLSX",
	src: ["https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.18.5/xlsx.full.min.js"],
	cache: true,
}, {
	lib: "ZingChart",
	src: "https://cdnjs.cloudflare.com/ajax/libs/zingchart/2.8.6/zingchart.min.js",
	cache: true,
}, {
	lib: "PlantUML",
	src: "https://cdn.rawgit.com/jmnote/plantuml-encoder/d133f316/dist/plantuml-encoder.min.js",
}, {
	lib: "DynaTable",
	src: "https://cdnjs.cloudflare.com/ajax/libs/Dynatable/0.3.1/jquery.dynatable.min.js",
	css: "https://cdnjs.cloudflare.com/ajax/libs/Dynatable/0.3.1/jquery.dynatable.min.css",
}, {
	lib: "JQuery Validate",
	src: "https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.14.0/jquery.validate.min.js",
}, {
	lib: "Underscore",
	src: `https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.13.6/underscore-min.js`,
	cache: true,
}, {
	lib: "Polymer",
	src: ["https://unpkg.com/@webcomponents/webcomponentsjs@next/webcomponents-loader.js", "https://unpkg.com/@polymer/polymer@3.0.0-pre.13/polymer-element.js?module", "https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/2.4.2/webcomponents-bundle.js"],
	cache: true,
	module: true,
	load: modules => {
		window.html = modules[1].html;
		window.PolymerElement = modules[1].PolymerElement;
		console.log(modules);
	},
}, {
	lib: "AccordionMenu",
	src: "http://www.jqueryscript.net/demo/Multilevel-Accordion-Menu-Plugin-For-jQuery/js/script.js",
	css: "http://www.jqueryscript.net/demo/Multilevel-Accordion-Menu-Plugin-For-jQuery/css/style.css"
}, {
	lib: "JSGrid",
	src: "http://js-grid.com/js/jsgrid.min.js",
	css: "http://js-grid.com/css/jsgrid.min.css"
}, {
	lib: "FancyForm",
	src: "http://fancyjs.com/fancy/build/fancyform-min.js",
	css: "http://fancyjs.com/fancy/build/fancyform-min.css"
}, {
	lib: 'nonoScroller',
	src: 'https://cdnjs.cloudflare.com/ajax/libs/jquery.nanoscroller/0.8.7/javascripts/jquery.nanoscroller.min.js',
	css: 'https://cdnjs.cloudflare.com/ajax/libs/jquery.nanoscroller/0.8.7/css/nanoscroller.min.css',
}, {
	lib: "Moment",
	src: "https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment-with-locales.min.js",
	cache: true,
}, {
	lib: "HTML2Canvas",
	src: "https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"
}, {
	lib: "JQuery Mobile",
	type: "mobile",
	src: "https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js",
	css: "https://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css"
}, {
	lib: "Juxtapose",
	src: "https://cdn.knightlab.com/libs/juxtapose/latest/js/juxtapose.min.js",
	css: "https://cdn.knightlab.com/libs/juxtapose/latest/css/juxtapose.css"
}, {
	lib: "TwentyTwenty",
	src: ["https://cdnjs.cloudflare.com/ajax/libs/mhayes-twentytwenty/1.0.0/js/jquery.event.move.min.js", "https://cdnjs.cloudflare.com/ajax/libs/mhayes-twentytwenty/1.0.0/js/jquery.twentytwenty.min.js"],
	css: ["https://cdnjs.cloudflare.com/ajax/libs/mhayes-twentytwenty/1.0.0/css/twentytwenty.min.css", "https://cdnjs.cloudflare.com/ajax/libs/mhayes-twentytwenty/1.0.0/css/foundation.min.css"],
}, {
	lib: "MD5",
	primary: true,
	src: "https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.2/components/core.js",
}, {
	lib: "Pako",
	src: "https://cdnjs.cloudflare.com/ajax/libs/pako/1.0.3/pako.min.js"
}, {
	lib: "PapaCSV",
	src: "https://cdnjs.cloudflare.com/ajax/libs/PapaParse/4.3.7/papaparse.min.js",
	cache: true,
}, {
	lib: "JQ Transform",
	src: "https://cdn.jsdelivr.net/jquery.jqtransform/1.1/jquery.jqtransform.js",
	css: "https://cdn.jsdelivr.net/jquery.jqtransform/1.1/jqtransform.css"
}, {
	lib: "Boostrap Select",
	src: "//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.2/js/bootstrap-select.min.js",
	css: "//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.2/css/bootstrap-select.min.css"
}, {
	lib: "Prettier",
	src: ["https://prettier.io/lib/standalone.js", "https://prettier.io/lib/parser-babylon.js"],
}, {
	lib: "ACEEditor",
	src: 'https://cdnjs.cloudflare.com/ajax/libs/ace/1.36.2/ace.min.js',
	cache: true,
}, {
	lib: "Beautifier",
	src: "https://cdnjs.cloudflare.com/ajax/libs/js-beautify/1.15.1/beautify.min.js",
	cache: true,
}, {
	lib: "prettyCheckable",
	src: "//cdn.jsdelivr.net/jquery.prettycheckable/1.2/prettyCheckable.js",
	css: "//cdn.jsdelivr.net/jquery.prettycheckable/1.2/prettyCheckable.css"
}, {
	lib: "JQuery UI",
	type: "desktop",
	src: "https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js",
	css: "https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"
}, {
	lib: 'GoJS',
	_src: 'https://cdnjs.cloudflare.com/ajax/libs/gojs/2.1.51/go-debug.min.js',
	src: 'https://cdnjs.cloudflare.com/ajax/libs/gojs/2.1.51/go.min.js',
	cache: true,
}, {
	lib: "Dojo",
	src: "https://ajax.googleapis.com/ajax/libs/dojo/1.10.4/dojo/dojo.js",
}, {
	lib: "ReactJS",
	src: ["https://cdnjs.cloudflare.com/ajax/libs/react/18.2.0/cjs/react.development.min.js", "https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.2.0/cjs/react-dom.development.min.js"],
	cache: true,
	requires: ["BabelJS"],
}, {
	lib: "ChartJS",
	src: "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.bundle.min.js",
	css: "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css",
	cache: true,
}, {
	lib: "EasyUI Mobile",
	src: "http://www.jeasyui.com/easyui/jquery.easyui.mobile.js",
	css: "http://www.jeasyui.com/easyui/themes/mobile.css",
}, {
	lib: "UIkit",
	type: "desktop",
	src: "https://cdnjs.cloudflare.com/ajax/libs/uikit/2.24.2/js/uikit.min.js",
	css: "https://cdnjs.cloudflare.com/ajax/libs/uikit/2.24.2/css/uikit.min.css"
}, {
	lib: "printThis",
	src: "https://cdnjs.cloudflare.com/ajax/libs/printThis/1.12.3/printThis.min.js",
}, {
	lib: "UIkit DatePicker",
	type: "desktop",
	src: "https://cdnjs.cloudflare.com/ajax/libs/uikit/2.22.0/js/components/datepicker.min.js",
	css: "https://cdnjs.cloudflare.com/ajax/libs/uikit/2.22.0/css/components/datepicker.css"
}, {
	lib: "UIkit Password",
	type: "desktop",
	src: "https://cdnjs.cloudflare.com/ajax/libs/uikit/2.22.0/js/components/form-password.min.js",
	css: "https://cdnjs.cloudflare.com/ajax/libs/uikit/2.22.0/css/components/form-password.min.css"
}, {
	lib: "Charts",
	type: "desktop",
	src: "https://cdnjs.cloudflare.com/ajax/libs/canvasjs/1.7.0/canvasjs.min.js",
	//src: "http://canvasjs.com/assets/script/canvasjs.min.js",
}, {
	lib: "Filters",
	src: "script/filters.js"
}, {
	lib: "doT",
	src: "https://cdnjs.cloudflare.com/ajax/libs/dot/1.0.3/doT.min.js"
}, {
	lib: "Handlebars",
	src: "https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.7.6/handlebars.min.js"
}, {
	lib: "Mustache",
	src: "https://unpkg.com/mustache@latest",
	cache: true,
	tools: [],
}, {
	lib: "EJS",
	_src: "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/embeddedjavascript/ejs_production.js",
	src: "https://cdn.jsdelivr.net/npm/ejs@3.1.10/ejs.min.js",
	cache: true,
}, {
	lib: "XML2JSON",
	src: "https://cdnjs.cloudflare.com/ajax/libs/x2js/1.2.0/xml2json.min.js",
	cache: true,
}, {
	lib: "XML-JS",
	src: "https://cdn.jsdelivr.net/npm/xml-js@1.6.11/dist/xml-js.min.js",
	cache: true
}, {
	lib: "JQuery NivoSlider",
	src: "https://cdnjs.cloudflare.com/ajax/libs/jquery-nivoslider/3.2/jquery.nivo.slider.min.js"
}, {
	lib: "NOTY",
	src: "https://cdnjs.cloudflare.com/ajax/libs/jquery-noty/2.4.1/packaged/jquery.noty.packaged.min.js",
	cache: true,
}, {
	lib: "JQuery Easing",
	src: "https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"
}, {
	lib: "Tabulator",
	src: "https://cdnjs.cloudflare.com/ajax/libs/tabulator/6.3.0/js/tabulator.min.js",
	css: "https://cdnjs.cloudflare.com/ajax/libs/tabulator/6.3.0/css/tabulator.min.css",
	cache: true,
}];
